apiVersion: v1
clusters:
- cluster:
    server:
  name:
contexts:
- context:
    cluster:
    namespace:
    user:
  name:
current-context:
kind: Config
preferences: {}
users:
- name:
  user:
    token:
